<a href="https://colab.research.google.com/github/janubro0125/Varsha-S-S-Data-Science/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
detail={"Name":["Varsha","Darsini","Ramesh","Tharsan"],"Domain":["Data Analyst","Data scientist","Data Analyst","Business Management"]}
detail

{'Name': ['Varsha', 'Darsini', 'Ramesh', 'Tharsan'],
 'Domain': ['Data Analyst',
  'Data scientist',
  'Data Analyst',
  'Business Management']}

In [17]:
data=pd.DataFrame(detail)
data

      Name               Domain
0   Varsha         Data Analyst
1  Darsini       Data scientist
2   Ramesh         Data Analyst
3  Tharsan  Business Management

In [19]:
dd=data.to_csv("details.csv")
dd

In [20]:
s=pd.read_csv("details.csv")
s

   Unnamed: 0     Name               Domain
0           0   Varsha         Data Analyst
1           1  Darsini       Data scientist
2           2   Ramesh         Data Analyst
3           3  Tharsan  Business Management

In [21]:
Name=s["Name"]
Name

0     Varsha
1    Darsini
2     Ramesh
3    Tharsan
Name: Name, dtype: object

In [24]:
Name=s.loc[0:1,"Name"]
Name

0     Varsha
1    Darsini
Name: Name, dtype: object

In [29]:
Skincare=pd.read_csv("Skincare_Brands_Sales_Dataset.csv")
Skincare

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Brand,Sales,Quantity,Discount,Profit
0,1,SK-2020-000001,07/28/2020,08/03/2020,Express Delivery,SC-13905,Sofia Chen,Retail,United States,New York,...,North,CLE-TO-22575562,Cleansers & Toners,Toner,Neutrogena Toner,Neutrogena,647.28,9,0.00,218.8444
1,2,SK-2023-000002,08/23/2023,08/29/2023,Express Delivery,SC-30926,Aria Patel,Pharmacy,United States,Houston,...,South,CLE-FA-66722344,Cleansers & Toners,Face Wash,Cetaphil Face Wash,Cetaphil,196.20,4,0.10,66.2868
2,3,SK-2022-000003,02/17/2022,02/18/2022,Standard Delivery,SC-70217,Sofia Chen,Retail,United States,Charlotte,...,East,MOI-EY-81971316,Moisturizers,Eye Cream,Clinique Eye Cream,Clinique,368.78,6,0.15,111.7050
3,4,SK-2023-000004,03/28/2023,03/30/2023,Same Day,SC-20458,Evelyn Anderson,Pharmacy,United States,Boston,...,North,MOI-BB-41244663,Moisturizers,BB Cream,SK-II BB Cream,SK-II,104.30,1,0.20,15.4145
4,5,SK-2021-000005,12/28/2021,12/30/2021,Same Day,SC-42087,Camila Lee,Retail,United States,Boston,...,North,SER-NI-31931511,Serums & Treatments,Niacinamide,Clinique Niacinamide,Clinique,255.14,2,0.15,99.6305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,SK-2023-009990,04/28/2023,05/05/2023,Same Day,SC-29099,Camila Lee,Retail,United States,Atlanta,...,South,SER-VI-77244507,Serums & Treatments,Vitamin C Serum,Neutrogena Vitamin C Serum,Neutrogena,222.47,9,0.05,57.6602
9990,9991,SK-2022-009991,11/24/2022,11/29/2022,Click & Collect,SC-68853,Amelia Moore,Retail,United States,Chicago,...,North,MOI-FA-68435425,Moisturizers,Face Cream,SK-II Face Cream,SK-II,890.97,6,0.15,396.3361
9991,9992,SK-2020-009992,07/11/2020,07/15/2020,Express Delivery,SC-68451,Ella Martin,Online,United States,Miami,...,South,SER-RE-16891910,Serums & Treatments,Retinol Serum,Neutrogena Retinol Serum,Neutrogena,164.44,4,0.00,36.2584
9992,9993,SK-2021-009993,06/02/2021,06/08/2021,Express Delivery,SC-17759,Mila Harris,Retail,United States,New York,...,North,CLE-FO-34840001,Cleansers & Toners,Foaming Cleanser,Cetaphil Foaming Cleanser,Cetaphil,79.90,5,0.15,28.6849
9993,9994,SK-2021-009994,04/11/2021,04/18/2021,Express Delivery,SC-53861,Sofia Chen,Retail,United States,Atlanta,...,South,MOI-NI-57581720,Moisturizers,Night Cream,Clinique Night Cream,Clinique,659.34,9,0.10,246.5994

In [30]:
print(Skincare.head())

   Row ID        Order ID  Order Date   Ship Date          Ship Mode  \
0       1  SK-2020-000001  07/28/2020  08/03/2020   Express Delivery
1       2  SK-2023-000002  08/23/2023  08/29/2023   Express Delivery
2       3  SK-2022-000003  02/17/2022  02/18/2022  Standard Delivery
3       4  SK-2023-000004  03/28/2023  03/30/2023           Same Day
4       5  SK-2021-000005  12/28/2021  12/30/2021           Same Day

  Customer ID    Customer Name   Segment        Country       City  ...  \
0    SC-13905       Sofia Chen    Retail  United States   New York  ...
1    SC-30926       Aria Patel  Pharmacy  United States    Houston  ...
2    SC-70217       Sofia Chen    Retail  United States  Charlotte  ...
3    SC-20458  Evelyn Anderson  Pharmacy  United States     Boston  ...
4    SC-42087       Camila Lee    Retail  United States     Boston  ...

  Region       Product ID             Category Sub-Category  \
0  North  CLE-TO-22575562   Cleansers & Toners        Toner
1  South  CLE-FA-66722344   Cleansers & Toners    Face Wash
2   East  MOI-EY-81971316         Moisturizers    Eye Cream
3  North  MOI-BB-41244663         Moisturizers     BB Cream
4  North  SER-NI-31931511  Serums & Treatments  Niacinamide

           Product Name       Brand   Sales Quantity  Discount    Profit
0      Neutrogena Toner  Neutrogena  647.28        9      0.00  218.8444
1    Cetaphil Face Wash    Cetaphil  196.20        4      0.10   66.2868
2    Clinique Eye Cream    Clinique  368.78        6      0.15  111.7050
3        SK-II BB Cream       SK-II  104.30        1      0.20   15.4145
4  Clinique Niacinamide    Clinique  255.14        2      0.15   99.6305

[5 rows x 22 columns]

In [31]:
print(Skincare.tail())

      Row ID        Order ID  Order Date   Ship Date         Ship Mode  \
9989    9990  SK-2023-009990  04/28/2023  05/05/2023          Same Day
9990    9991  SK-2022-009991  11/24/2022  11/29/2022   Click & Collect
9991    9992  SK-2020-009992  07/11/2020  07/15/2020  Express Delivery
9992    9993  SK-2021-009993  06/02/2021  06/08/2021  Express Delivery
9993    9994  SK-2021-009994  04/11/2021  04/18/2021  Express Delivery

     Customer ID Customer Name Segment        Country      City  ... Region  \
9989    SC-29099    Camila Lee  Retail  United States   Atlanta  ...  South
9990    SC-68853  Amelia Moore  Retail  United States   Chicago  ...  North
9991    SC-68451   Ella Martin  Online  United States     Miami  ...  South
9992    SC-17759   Mila Harris  Retail  United States  New York  ...  North
9993    SC-53861    Sofia Chen  Retail  United States   Atlanta  ...  South

           Product ID             Category      Sub-Category  \
9989  SER-VI-77244507  Serums & Treatments   Vitamin C Serum
9990  MOI-FA-68435425         Moisturizers        Face Cream
9991  SER-RE-16891910  Serums & Treatments     Retinol Serum
9992  CLE-FO-34840001   Cleansers & Toners  Foaming Cleanser
9993  MOI-NI-57581720         Moisturizers       Night Cream

                    Product Name       Brand   Sales Quantity  Discount  \
9989  Neutrogena Vitamin C Serum  Neutrogena  222.47        9      0.05
9990            SK-II Face Cream       SK-II  890.97        6      0.15
9991    Neutrogena Retinol Serum  Neutrogena  164.44        4      0.00
9992   Cetaphil Foaming Cleanser    Cetaphil   79.90        5      0.15
9993        Clinique Night Cream    Clinique  659.34        9      0.10

        Profit
9989   57.6602
9990  396.3361
9991   36.2584
9992   28.6849
9993  246.5994

[5 rows x 22 columns]

In [32]:
print(Skincare.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Brand          9994 non-null   object
 18  Sales          9994 non-null   float64
 19  Quantity       9994 non-null   int64
 20  Discount       9994 non-null   float64
 21  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(16)
memory usage: 1.7+ MB
None

In [33]:
print(Skincare.describe())

            Row ID   Postal Code        Sales     Quantity     Discount  \
count  9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   4997.500000  48900.109466   437.827597     5.503102     0.083215
std    2885.163629  33206.049108   390.018594     2.871552     0.074347
min       1.000000   2101.000000     5.120000     1.000000     0.000000
25%    2499.250000  28201.000000   140.547500     3.000000     0.000000
50%    4997.500000  33101.000000   314.795000     5.500000     0.100000
75%    7495.750000  90001.000000   620.170000     8.000000     0.150000
max    9994.000000  98101.000000  2180.700000    10.000000     0.200000

            Profit
count  9994.000000
mean    138.539785
std     137.914219
min       0.833800
25%      39.665925
50%      91.596450
75%     192.297400
max     961.596500